// Emacs style mode select   -*- C++ -*- 
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// DESCRIPTION:
//	Printed strings, french translation.
//
//-----------------------------------------------------------------------------


if (typeof __D_FRENCH__ == "undefined"){
export const __D_FRENCH__ :boolean = true;

//
// D_Main.C
//
export const D_DEVSTR	"MODE DEVELOPPEMENT ON.\n"
export const D_CDROM		"VERSION CD-ROM: DEFAULT.CFG DANS C:\\DOOMDATA\n"

//
//	M_Menu.C
//
export const PRESSKEY 	"APPUYEZ SUR UNE TOUCHE."
export const PRESSYN 	"APPUYEZ SUR Y OU N"
export const QUITMSG		"VOUS VOULEZ VRAIMENT\nQUITTER CE SUPER JEU?"
export const LOADNET 	"VOUS NE POUVEZ PAS CHARGER\nUN JEU EN RESEAU!\n\n"PRESSKEY
export const QLOADNET	"CHARGEMENT RAPIDE INTERDIT EN RESEAU!\n\n"PRESSKEY
export const QSAVESPOT	"VOUS N'AVEZ PAS CHOISI UN EMPLACEMENT!\n\n"PRESSKEY
export const SAVEDEAD 	"VOUS NE POUVEZ PAS SAUVER SI VOUS NE JOUEZ "\
"PAS!\n\n"PRESSKEY
export const QSPROMPT 	"SAUVEGARDE RAPIDE DANS LE FICHIER \n\n'%s'?\n\n"PRESSYN
export const QLPROMPT	"VOULEZ-VOUS CHARGER LA SAUVEGARDE"\
"\n\n'%s'?\n\n"PRESSYN
export const NEWGAME		"VOUS NE POUVEZ PAS LANCER\n"\
"UN NOUVEAU JEU SUR RESEAU.\n\n"PRESSKEY
export const NIGHTMARE	"VOUS CONFIRMEZ? CE NIVEAU EST\n"\
"VRAIMENT IMPITOYABLE!n"PRESSYN
export const SWSTRING	"CECI EST UNE VERSION SHAREWARE DE DOOM.\n\n"\
"VOUS DEVRIEZ COMMANDER LA TRILOGIE COMPLETE.\n\n"PRESSKEY
export const MSGOFF		"MESSAGES OFF"
export const MSGON		"MESSAGES ON"
export const NETEND		"VOUS NE POUVEZ PAS METTRE FIN A UN JEU SUR "\
"RESEAU!\n\n"PRESSKEY
export const ENDGAME		"VOUS VOULEZ VRAIMENT METTRE FIN AU JEU?\n\n"PRESSYN

export const DOSY		"(APPUYEZ SUR Y POUR REVENIR AU OS.)"

export const DETAILHI	"GRAPHISMES MAXIMUM "
export const DETAILLO	"GRAPHISMES MINIMUM "
export const GAMMALVL0	"CORRECTION GAMMA OFF"
export const GAMMALVL1	"CORRECTION GAMMA NIVEAU 1"
export const GAMMALVL2	"CORRECTION GAMMA NIVEAU 2"
export const GAMMALVL3	"CORRECTION GAMMA NIVEAU 3"
export const GAMMALVL4	"CORRECTION GAMMA NIVEAU 4"
export const EMPTYSTRING	"EMPLACEMENT VIDE"

//
//	P_inter.C
//
export const GOTARMOR	"ARMURE RECUPEREE."
export const GOTMEGA		"MEGA-ARMURE RECUPEREE!"
export const GOTHTHBONUS	"BONUS DE SANTE RECUPERE."
export const GOTARMBONUS	"BONUS D'ARMURE RECUPERE."
export const GOTSTIM		"STIMPACK RECUPERE."
export const GOTMEDINEED	"MEDIKIT RECUPERE. VOUS EN AVEZ VRAIMENT BESOIN!"
export const GOTMEDIKIT	"MEDIKIT RECUPERE."
export const GOTSUPER	"SUPERCHARGE!"

export const GOTBLUECARD	"CARTE MAGNETIQUE BLEUE RECUPEREE."
export const GOTYELWCARD	"CARTE MAGNETIQUE JAUNE RECUPEREE."
export const GOTREDCARD	"CARTE MAGNETIQUE ROUGE RECUPEREE."
export const GOTBLUESKUL	"CLEF CRANE BLEUE RECUPEREE."
export const GOTYELWSKUL	"CLEF CRANE JAUNE RECUPEREE."
export const GOTREDSKULL	"CLEF CRANE ROUGE RECUPEREE."

export const GOTINVUL	"INVULNERABILITE!"
export const GOTBERSERK	"BERSERK!"
export const GOTINVIS	"INVISIBILITE PARTIELLE "
export const GOTSUIT		"COMBINAISON ANTI-RADIATIONS "
export const GOTMAP		"CARTE INFORMATIQUE "
export const GOTVISOR	"VISEUR A AMPLIFICATION DE LUMIERE "
export const GOTMSPHERE	"MEGASPHERE!"

export const GOTCLIP		"CHARGEUR RECUPERE."
export const GOTCLIPBOX	"BOITE DE BALLES RECUPEREE."
export const GOTROCKET	"ROQUETTE RECUPEREE."
export const GOTROCKBOX	"CAISSE DE ROQUETTES RECUPEREE."
export const GOTCELL		"CELLULE D'ENERGIE RECUPEREE."
export const GOTCELLBOX	"PACK DE CELLULES D'ENERGIE RECUPERE."
export const GOTSHELLS	"4 CARTOUCHES RECUPEREES."
export const GOTSHELLBOX	"BOITE DE CARTOUCHES RECUPEREE."
export const GOTBACKPACK	"SAC PLEIN DE MUNITIONS RECUPERE!"

export const GOTBFG9000	"VOUS AVEZ UN BFG9000!  OH, OUI!"
export const GOTCHAINGUN	"VOUS AVEZ LA MITRAILLEUSE!"
export const GOTCHAINSAW	"UNE TRONCONNEUSE!"
export const GOTLAUNCHER	"VOUS AVEZ UN LANCE-ROQUETTES!"
export const GOTPLASMA	"VOUS AVEZ UN FUSIL A PLASMA!"
export const GOTSHOTGUN	"VOUS AVEZ UN FUSIL!"
export const GOTSHOTGUN2	"VOUS AVEZ UN SUPER FUSIL!"

//
// P_Doors.C
//
export const PD_BLUEO	"IL VOUS FAUT UNE CLEF BLEUE"
export const PD_REDO		"IL VOUS FAUT UNE CLEF ROUGE"
export const PD_YELLOWO	"IL VOUS FAUT UNE CLEF JAUNE"
export const PD_BLUEK	PD_BLUEO
export const PD_REDK		PD_REDO
export const PD_YELLOWK	PD_YELLOWO

//
//	G_game.C
//
export const GGSAVED		"JEU SAUVEGARDE."

//
//	HU_stuff.C
//
export const HUSTR_MSGU	"[MESSAGE NON ENVOYE]"

export const HUSTR_E1M1	"E1M1: HANGAR"
export const HUSTR_E1M2	"E1M2: USINE NUCLEAIRE "
export const HUSTR_E1M3	"E1M3: RAFFINERIE DE TOXINES "
export const HUSTR_E1M4	"E1M4: CENTRE DE CONTROLE "
export const HUSTR_E1M5	"E1M5: LABORATOIRE PHOBOS "
export const HUSTR_E1M6	"E1M6: TRAITEMENT CENTRAL "
export const HUSTR_E1M7	"E1M7: CENTRE INFORMATIQUE "
export const HUSTR_E1M8	"E1M8: ANOMALIE PHOBOS "
export const HUSTR_E1M9	"E1M9: BASE MILITAIRE "

export const HUSTR_E2M1	"E2M1: ANOMALIE DEIMOS "
export const HUSTR_E2M2	"E2M2: ZONE DE CONFINEMENT "
export const HUSTR_E2M3	"E2M3: RAFFINERIE"
export const HUSTR_E2M4	"E2M4: LABORATOIRE DEIMOS "
export const HUSTR_E2M5	"E2M5: CENTRE DE CONTROLE "
export const HUSTR_E2M6	"E2M6: HALLS DES DAMNES "
export const HUSTR_E2M7	"E2M7: CUVES DE REPRODUCTION "
export const HUSTR_E2M8	"E2M8: TOUR DE BABEL "
export const HUSTR_E2M9	"E2M9: FORTERESSE DU MYSTERE "

export const HUSTR_E3M1	"E3M1: DONJON DE L'ENFER "
export const HUSTR_E3M2	"E3M2: BOURBIER DU DESESPOIR "
export const HUSTR_E3M3	"E3M3: PANDEMONIUM"
export const HUSTR_E3M4	"E3M4: MAISON DE LA DOULEUR "
export const HUSTR_E3M5	"E3M5: CATHEDRALE PROFANE "
export const HUSTR_E3M6	"E3M6: MONT EREBUS"
export const HUSTR_E3M7	"E3M7: LIMBES"
export const HUSTR_E3M8	"E3M8: DIS"
export const HUSTR_E3M9	"E3M9: CLAPIERS"

export const HUSTR_1		"NIVEAU 1: ENTREE "
export const HUSTR_2		"NIVEAU 2: HALLS SOUTERRAINS "
export const HUSTR_3		"NIVEAU 3: LE FEU NOURRI "
export const HUSTR_4		"NIVEAU 4: LE FOYER "
export const HUSTR_5		"NIVEAU 5: LES EGOUTS "
export const HUSTR_6		"NIVEAU 6: LE BROYEUR "
export const HUSTR_7		"NIVEAU 7: L'HERBE DE LA MORT"
export const HUSTR_8		"NIVEAU 8: RUSES ET PIEGES "
export const HUSTR_9		"NIVEAU 9: LE PUITS "
export const HUSTR_10	"NIVEAU 10: BASE DE RAVITAILLEMENT "
export const HUSTR_11	"NIVEAU 11: LE CERCLE DE LA MORT!"

export const HUSTR_12	"NIVEAU 12: L'USINE "
export const HUSTR_13	"NIVEAU 13: LE CENTRE VILLE"
export const HUSTR_14	"NIVEAU 14: LES ANTRES PROFONDES "
export const HUSTR_15	"NIVEAU 15: LA ZONE INDUSTRIELLE "
export const HUSTR_16	"NIVEAU 16: LA BANLIEUE"
export const HUSTR_17	"NIVEAU 17: LES IMMEUBLES"
export const HUSTR_18	"NIVEAU 18: LA COUR "
export const HUSTR_19	"NIVEAU 19: LA CITADELLE "
export const HUSTR_20	"NIVEAU 20: JE T'AI EU!"

export const HUSTR_21	"NIVEAU 21: LE NIRVANA"
export const HUSTR_22	"NIVEAU 22: LES CATACOMBES "
export const HUSTR_23	"NIVEAU 23: LA GRANDE FETE "
export const HUSTR_24	"NIVEAU 24: LE GOUFFRE "
export const HUSTR_25	"NIVEAU 25: LES CHUTES DE SANG"
export const HUSTR_26	"NIVEAU 26: LES MINES ABANDONNEES "
export const HUSTR_27	"NIVEAU 27: CHEZ LES MONSTRES "
export const HUSTR_28	"NIVEAU 28: LE MONDE DE L'ESPRIT "
export const HUSTR_29	"NIVEAU 29: LA LIMITE "
export const HUSTR_30	"NIVEAU 30: L'ICONE DU PECHE "

export const HUSTR_31	"NIVEAU 31: WOLFENSTEIN"
export const HUSTR_32	"NIVEAU 32: LE MASSACRE"


export const HUSTR_CHATMACRO1	"JE SUIS PRET A LEUR EN FAIRE BAVER!"
export const HUSTR_CHATMACRO2	"JE VAIS BIEN."
export const HUSTR_CHATMACRO3	"JE N'AI PAS L'AIR EN FORME!"
export const HUSTR_CHATMACRO4	"AU SECOURS!"
export const HUSTR_CHATMACRO5	"TU CRAINS!"
export const HUSTR_CHATMACRO6	"LA PROCHAINE FOIS, MINABLE..."
export const HUSTR_CHATMACRO7	"VIENS ICI!"
export const HUSTR_CHATMACRO8	"JE VAIS M'EN OCCUPER."
export const HUSTR_CHATMACRO9	"OUI"
export const HUSTR_CHATMACRO0	"NON"

export const HUSTR_TALKTOSELF1	"VOUS PARLEZ TOUT SEUL "
export const HUSTR_TALKTOSELF2	"QUI EST LA?"
export const HUSTR_TALKTOSELF3	"VOUS VOUS FAITES PEUR "
export const HUSTR_TALKTOSELF4	"VOUS COMMENCEZ A DELIRER "
export const HUSTR_TALKTOSELF5	"VOUS ETES LARGUE..."

export const HUSTR_MESSAGESENT	"[MESSAGE ENVOYE]"

// The following should NOT be changed unless it seems
// just AWFULLY necessary

export const HUSTR_PLRGREEN	"VERT: "
export const HUSTR_PLRINDIGO	"INDIGO: "
export const HUSTR_PLRBROWN	"BRUN: "
export const HUSTR_PLRRED		"ROUGE: "

export const HUSTR_KEYGREEN	'g'	// french key should be "V"
export const HUSTR_KEYINDIGO	'i'	
export const HUSTR_KEYBROWN	'b'	
export const HUSTR_KEYRED		'r'

//
//	AM_map.C
//

export const AMSTR_FOLLOWON		"MODE POURSUITE ON"
export const AMSTR_FOLLOWOFF		"MODE POURSUITE OFF"

export const AMSTR_GRIDON		"GRILLE ON"
export const AMSTR_GRIDOFF		"GRILLE OFF"

export const AMSTR_MARKEDSPOT	"REPERE MARQUE "
export const AMSTR_MARKSCLEARED	"REPERES EFFACES "

//
//	ST_stuff.C
//

export const STSTR_MUS		"CHANGEMENT DE MUSIQUE "
export const STSTR_NOMUS		"IMPOSSIBLE SELECTION"
export const STSTR_DQDON		"INVULNERABILITE ON "
export const STSTR_DQDOFF		"INVULNERABILITE OFF"

export const STSTR_KFAADDED		"ARMEMENT MAXIMUM! "
export const STSTR_FAADDED		"ARMES (SAUF CLEFS) AJOUTEES"

export const STSTR_NCON		"BARRIERES ON"
export const STSTR_NCOFF		"BARRIERES OFF"

export const STSTR_BEHOLD		" inVuln, Str, Inviso, Rad, Allmap, or Lite-amp"
export const STSTR_BEHOLDX		"AMELIORATION ACTIVEE"

export const STSTR_CHOPPERS		"... DOESN'T SUCK - GM"
export const STSTR_CLEV		"CHANGEMENT DE NIVEAU..."

//
//	F_Finale.C
//
export const E1TEXT	"APRES AVOIR VAINCU LES GROS MECHANTS\n"\
"ET NETTOYE LA BASE LUNAIRE, VOUS AVEZ\n"\
"GAGNE, NON? PAS VRAI? OU EST DONC VOTRE\n"\
" RECOMPENSE ET VOTRE BILLET DE\n"\
"RETOUR? QU'EST-QUE CA VEUT DIRE?CE"\
"N'EST PAS LA FIN ESPEREE!\n"\
"\n" \
"CA SENT LA VIANDE PUTREFIEE, MAIS\n"\
"ON DIRAIT LA BASE DEIMOS. VOUS ETES\n"\
"APPAREMMENT BLOQUE AUX PORTES DE L'ENFER.\n"\
"LA SEULE ISSUE EST DE L'AUTRE COTE.\n"\
"\n"\
"POUR VIVRE LA SUITE DE DOOM, JOUEZ\n"\
"A 'AUX PORTES DE L'ENFER' ET A\n"\
"L'EPISODE SUIVANT, 'L'ENFER'!\n"
				
export const E2TEXT	"VOUS AVEZ REUSSI. L'INFAME DEMON\n"\
"QUI CONTROLAIT LA BASE LUNAIRE DE\n"\
"DEIMOS EST MORT, ET VOUS AVEZ\n"\
"TRIOMPHE! MAIS... OU ETES-VOUS?\n"\
"VOUS GRIMPEZ JUSQU'AU BORD DE LA\n"\
"LUNE ET VOUS DECOUVREZ L'ATROCE\n"\
"VERITE.\n" \
"\n"\
"DEIMOS EST AU-DESSUS DE L'ENFER!\n"\
"VOUS SAVEZ QUE PERSONNE NE S'EN\n"\
"EST JAMAIS ECHAPPE, MAIS CES FUMIERS\n"\
"VONT REGRETTER DE VOUS AVOIR CONNU!\n"\
"VOUS REDESCENDEZ RAPIDEMENT VERS\n"\
"LA SURFACE DE L'ENFER.\n"\
"\n" \
"VOICI MAINTENANT LE CHAPITRE FINAL DE\n"\
"DOOM! -- L'ENFER."

export const E3TEXT	"LE DEMON ARACHNEEN ET REPUGNANT\n"\
"QUI A DIRIGE L'INVASION DES BASES\n"\
"LUNAIRES ET SEME LA MORT VIENT DE SE\n"\
"FAIRE PULVERISER UNE FOIS POUR TOUTES.\n"\
"\n"\
"UNE PORTE SECRETE S'OUVRE. VOUS ENTREZ.\n"\
"VOUS AVEZ PROUVE QUE VOUS POUVIEZ\n"\
"RESISTER AUX HORREURS DE L'ENFER.\n"\
"IL SAIT ETRE BEAU JOUEUR, ET LORSQUE\n"\
"VOUS SORTEZ, VOUS REVOYEZ LES VERTES\n"\
"PRAIRIES DE LA TERRE, VOTRE PLANETE.\n"\
"\n"\
"VOUS VOUS DEMANDEZ CE QUI S'EST PASSE\n"\
"SUR TERRE PENDANT QUE VOUS AVEZ\n"\
"COMBATTU LE DEMON. HEUREUSEMENT,\n"\
"AUCUN GERME DU MAL N'A FRANCHI\n"\
"CETTE PORTE AVEC VOUS..."



// after level 6, put this:

export const C1TEXT	"VOUS ETES AU PLUS PROFOND DE L'ASTROPORT\n" \
"INFESTE DE MONSTRES, MAIS QUELQUE CHOSE\n" \
"NE VA PAS. ILS ONT APPORTE LEUR PROPRE\n" \
"REALITE, ET LA TECHNOLOGIE DE L'ASTROPORT\n" \
"EST AFFECTEE PAR LEUR PRESENCE.\n" \
"\n"\
"DEVANT VOUS, VOUS VOYEZ UN POSTE AVANCE\n" \
"DE L'ENFER, UNE ZONE FORTIFIEE. SI VOUS\n" \
"POUVEZ PASSER, VOUS POURREZ PENETRER AU\n" \
"COEUR DE LA BASE HANTEE ET TROUVER \n" \
"L'INTERRUPTEUR DE CONTROLE QUI GARDE LA \n" \
"POPULATION DE LA TERRE EN OTAGE."

// After level 11, put this:

export const C2TEXT	"VOUS AVEZ GAGNE! VOTRE VICTOIRE A PERMIS\n" \
"A L'HUMANITE D'EVACUER LA TERRE ET \n"\
"D'ECHAPPER AU CAUCHEMAR. VOUS ETES \n"\
"MAINTENANT LE DERNIER HUMAIN A LA SURFACE \n"\
"DE LA PLANETE. VOUS ETES ENTOURE DE \n"\
"MUTANTS CANNIBALES, D'EXTRATERRESTRES \n"\
"CARNIVORES ET D'ESPRITS DU MAL. VOUS \n"\
"ATTENDEZ CALMEMENT LA MORT, HEUREUX \n"\
"D'AVOIR PU SAUVER VOTRE RACE.\n"\
"MAIS UN MESSAGE VOUS PARVIENT SOUDAIN\n"\
"DE L'ESPACE: \"NOS CAPTEURS ONT LOCALISE\n"\
"LA SOURCE DE L'INVASION EXTRATERRESTRE.\n"\
"SI VOUS Y ALLEZ, VOUS POURREZ PEUT-ETRE\n"\
"LES ARRETER. LEUR BASE EST SITUEE AU COEUR\n"\
"DE VOTRE VILLE NATALE, PRES DE L'ASTROPORT.\n"\
"VOUS VOUS RELEVEZ LENTEMENT ET PENIBLEMENT\n"\
"ET VOUS REPARTEZ POUR LE FRONT."

// After level 20, put this:

export const C3TEXT	"VOUS ETES AU COEUR DE LA CITE CORROMPUE,\n"\
"ENTOURE PAR LES CADAVRES DE VOS ENNEMIS.\n"\
"VOUS NE VOYEZ PAS COMMENT DETRUIRE LA PORTE\n"\
"DES CREATURES DE CE COTE. VOUS SERREZ\n"\
"LES DENTS ET PLONGEZ DANS L'OUVERTURE.\n"\
"\n"\
"IL DOIT Y AVOIR UN MOYEN DE LA FERMER\n"\
"DE L'AUTRE COTE. VOUS ACCEPTEZ DE\n"\
"TRAVERSER L'ENFER POUR LE FAIRE?"

// After level 29, put this:

export const C4TEXT	"LE VISAGE HORRIBLE D'UN DEMON D'UNE\n"\
"TAILLE INCROYABLE S'EFFONDRE DEVANT\n"\
"VOUS LORSQUE VOUS TIREZ UNE SALVE DE\n"\
"ROQUETTES DANS SON CERVEAU. LE MONSTRE\n"\
"SE RATATINE, SES MEMBRES DECHIQUETES\n"\
"SE REPANDANT SUR DES CENTAINES DE\n"\
"KILOMETRES A LA SURFACE DE L'ENFER.\n"\
"\n"\
"VOUS AVEZ REUSSI. L'INVASION N'AURA.\n"\
"PAS LIEU. LA TERRE EST SAUVEE. L'ENFER\n"\
"EST ANEANTI. EN VOUS DEMANDANT OU IRONT\n"\
"MAINTENANT LES DAMNES, VOUS ESSUYEZ\n"\
"VOTRE FRONT COUVERT DE SUEUR ET REPARTEZ\n"\
"VERS LA TERRE. SA RECONSTRUCTION SERA\n"\
"BEAUCOUP PLUS DROLE QUE SA DESTRUCTION.\n"

// Before level 31, put this:

export const C5TEXT	"FELICITATIONS! VOUS AVEZ TROUVE LE\n"\
"NIVEAU SECRET! IL SEMBLE AVOIR ETE\n"\
"CONSTRUIT PAR LES HUMAINS. VOUS VOUS\n"\
"DEMANDEZ QUELS PEUVENT ETRE LES\n"\
"HABITANTS DE CE COIN PERDU DE L'ENFER."

// Before level 32, put this:

export const C6TEXT	"FELICITATIONS! VOUS AVEZ DECOUVERT\n"\
"LE NIVEAU SUPER SECRET! VOUS FERIEZ\n"\
"MIEUX DE FONCER DANS CELUI-LA!\n"

//
// Character cast strings F_FINALE.C
//
export const CC_ZOMBIE	"ZOMBIE"
export const CC_SHOTGUN	"TYPE AU FUSIL"
export const CC_HEAVY	"MEC SUPER-ARME"
export const CC_IMP		"DIABLOTIN"
export const CC_DEMON	"DEMON"
export const CC_LOST		"AME PERDUE"
export const CC_CACO		"CACODEMON"
export const CC_HELL		"CHEVALIER DE L'ENFER"
export const CC_BARON	"BARON DE L'ENFER"
export const CC_ARACH	"ARACHNOTRON"
export const CC_PAIN		"ELEMENTAIRE DE LA DOULEUR"
export const CC_REVEN	"REVENANT"
export const CC_MANCU	"MANCUBUS"
export const CC_ARCH		"ARCHI-INFAME"
export const CC_SPIDER	"L'ARAIGNEE CERVEAU"
export const CC_CYBER	"LE CYBERDEMON"
export const CC_HERO		"NOTRE HEROS"



#endif
//-----------------------------------------------------------------------------
//
// $Log:$
//
//-----------------------------------------------------------------------------


